<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Per-product FAQ: [{ "q": "...", "a": "..." }].
 *
 * A JSON column rather than a `product_faqs` table. The list is always read
 * whole, with the product, and never queried by question — so a table would buy
 * a join and an ordering column and nothing else. It is generated by
 * tools/gen-product-faq.py from data the product already carries (barcode,
 * origin, dietary flags, MOQ, price tiers), which is also why nothing here is
 * free text a merchant maintains by hand.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('products', function (Blueprint $table): void {
            $table->json('faq')->nullable()->after('description');
        });
    }

    public function down(): void
    {
        Schema::table('products', function (Blueprint $table): void {
            $table->dropColumn('faq');
        });
    }
};
